name: CI/CD dbt_hypermarche

push:
    branches: ["**"] # On lance sur toutes les branches
  pull_request:
    branches: ["**"]
    
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static_checks:
    name: ğŸ” Static Checks (Ruff, Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # L'image ubuntu-latest a dÃ©jÃ  python, on configure juste uv proprement
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"
          enable-cache: true # GÃ¨re automatiquement le cache des dÃ©pendances !
          cache-dependency-glob: "uv.lock"

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Run Ruff
        run: uv run ruff check .

      - name: dbt compile check âš™ï¸
        run: cd dbt && uv run dbt compile

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  build_and_deploy:
    name: ğŸ—ï¸ dbt Build & Deploy
    needs: static_checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/solution'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv & Python 3.13
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Sync dependencies
        run: uv sync --frozen

      - name: Generate dbt build âš™ï¸
        run: cd dbt && uv run dbt build

      - name: Generate dbt docs & colibri ğŸ“–ğŸ¦
        run: |
          cd dbt
          uv run dbt docs generate
          uv run colibri generate --output-dir target/colibri

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dbt/target

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
